# Image and version of keycloak.
image: sundeer/keycloak
version: v1.1.0

ingress:
  #Set to true to create an ingress
  enabled: true
  # Hostname for the ingress
  #hostname:
  #Only used if hostname is not set. Suffix for the release name to find the hostname
  hostbase: corngoodness.com
