apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-cleanup
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-delete
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}-cleanup
      labels:
{{ include "labels" . | indent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: post-install-job
        image: "lachlanevenson/k8s-kubectl:v1.5.2"
        command:
        - sh
        - -c
        - "kubectl delete secret {{ template "fullname" . }}; kubectl delete job {{ template "fullname" . }}-cleanup"