apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  selector:
{{ include "template.labels" . | indent 4 }}
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
