{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - hosts:
    - {{ template "hostname" . }}
    secretName: {{ template "fullname" . }}-tls
  rules:
  - host: {{ template "hostname" . }}
    http:
     paths:
     - path: /
       backend:
         serviceName: {{ template "fullname" . }}
         servicePort: http
{{- end }}
