apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install
data:
  username: {{ "postgres" | b64enc | quote }}
  password: {{ randAlphaNum 40 | b64enc | quote }}
