# version of postgres. See https://hub.docker.com/r/library/postgres/tags/
version: 9.6.3

# persistence of the postgres data
persistence:
  # Use false to just use an empty dir
  enabled: true
  size: 5Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 256Mi
    cpu: 100m
